# PostgreSQL image from https://github.com/sameersbn/docker-postgresq
# To get into  shell access: winpty docker exec -it db_local_budget bash

FROM sameersbn/postgresql:10-2

ENV PG_TRUST_LOCALNET=true \
	DB_USER=admin \
	DB_PASS=Admin.123 \
	DB_NAME=budget